impudo-ui/impudo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from interface import urls as template_urls
from interface import views
from interface.admin import admin_site

urlpatterns = [
    url(r'^$', views.home_page, name='home'),
    url(r'^templates/', include(template_urls)),
    #url(r'^manage/', include(admin.site.urls)),
    url(r'^manage/', include(admin_site.urls)),
]

impudo-ui/interface/urls.py
from django.conf.urls import url
from interface import views

urlpatterns = [
    url(r'^new$', views.new_template, name='new_template'),
    url(r'^(\d+)/$', views.view_template, name='view_template'),
        ]

impudo-ui/interface/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.dispatch import receiver

from StringIO import StringIO
from PIL import Image as Img
import os

from impudo.settings import BASE_DIR
from impudo.settings import MEDIA_ROOT

class Template(models.Model):
    url_abbr = models.TextField(verbose_name='Name')
    url = models.URLField()
    desc = models.TextField(verbose_name='Description')

    def __str__(self):
        return self.url_abbr

    def get_absolute_url(self):
        return reverse('view_template', args=[self.id])

class Crawler(models.Model):
    template = models.ForeignKey(Template, default=None)
    xpath = models.TextField()
    content = models.TextField()
    url = models.URLField()
    active = models.IntegerField(default=0)

    def __str__(self):
        return str(self.pk)

class Record(models.Model):
    template = models.ForeignKey(Template, default=None)
    title = models.CharField(max_length=200, default=None)
    url = models.URLField()
    result = models.TextField()
    price = models.CharField(max_length=100, blank=True)
    dimensions = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return str(self.pk)


class CrawlerImgPath(models.Model):
    template = models.ForeignKey(Template, default=None)
    xpath = models.TextField()
    active = models.IntegerField(default=0)

class CrawlerImg(models.Model):
    img_path = models.ForeignKey(CrawlerImgPath, default=None)
    path = models.CharField(max_length=500)

    def img(self):
        return u'<img src="../../../../media/%s" width="100"/>' % (self.path)

class Image(models.Model):
    record = models.ForeignKey(Record, default=None)
    path = models.CharField(max_length=500)

    def img(self):
        return u'<img src="../../../../media/%s" width="100"/>' % (self.path)
    img.short_description = 'Image'
    img.allow_tags = True

    def __str__(self):
        return str(self.pk)

@receiver(models.signals.post_delete, sender=CrawlerImg)
def CrawlerImg_delete(sender, instance, *args, **kwargs):
    try:
        os.remove(os.path.join(MEDIA_ROOT, instance.path))
    except OSError:
        pass

@receiver(models.signals.post_delete, sender=Image)
def Image_delete(sender, instance, *args, **kwargs):
    try:
        os.remove(os.path.join(MEDIA_ROOT, instance.path))
    except OSError:
        pass

impudo-ui/interface/forms.py
import re

import ast
from django import forms

from interface.models import Template, Crawler, CrawlerImg, CrawlerImgPath
from interface.analyzer.analyzer import Analyzer


EMPTY_URL_ERROR = 'You need to supply a URL'
EMPTY_DESC_ERROR = 'You need to supply a description'

SCRAPE_TEXT = '''ALVAR AALTO
MODEL 2145, 1942/ 1950S
MORE
EMBRU, SWITZERLAND

SOLD
'''

class TemplateForm(forms.models.ModelForm):

    class Meta:
        model = Template
        fields = ('url', 'desc',)
        widgets = {
                'url': forms.fields.URLInput(attrs={
                    'placeholder': 'Enter a url, e.g. http://www.etoz.ch/model-2145/',
                    'class': 'form-control input-lg',
                }),
                'desc': forms.Textarea(attrs={
                    'placeholder': 'Enter text to scrape, e.g.\n' + SCRAPE_TEXT,
                    'class': 'form-control input-lg',
                    }),
            }
        error_messages = {
                'url': {'required': EMPTY_URL_ERROR},
                'desc': {'required': EMPTY_DESC_ERROR},
                }

    def save(self):
        '''
        Saves the missing url_abbr field by pattern matching.
        '''
        #template = super(TemplateForm, self).save(commit=False)
        url = self['url'].value()
        match = re.search(r'^(http://|https://)(www.)?(?P<abbr>.*?)\.', url)
        url_abbr = match.group('abbr') if match else url
        self.instance.url_abbr = url_abbr
        return super(TemplateForm, self).save()

    def analyze(self):
        desc = self['desc'].value().replace('\r', '')
        url = self['url'].value()
        analyzer = Analyzer(url)
        paths = analyzer.analyze(desc)
        img_paths = analyzer.analyze_img()
        for path, content in paths:
            Crawler.objects.create(template= self.instance, xpath= path,
                                   content= content, url= url)

        for path in img_paths:
            crawler = CrawlerImgPath.objects.create(template= self.instance, xpath= path)
            for img in analyzer.search_imgs(path[:]):
                CrawlerImg.objects.create(img_path_id= crawler.pk, path= analyzer.download_img(img))

    def save_active_paths(self, active):
        url = self['url'].value()

        for crawler in active:
            #TODO: delete active xpaths from all_paths
            Crawler.objects.create(template= self.instance, xpath= crawler.xpath,
                                   content= crawler.content, url= url, active= 1)

    def save_active_imgs(self, active):
        url = self['url'].value()
        analyzer = Analyzer(url)
        for img in active:
            crawler = CrawlerImgPath.objects.create(template= self.instance, xpath= img.xpath, active= 1)
            for i in analyzer.search_imgs(ast.literal_eval(img.xpath)[:]):
                CrawlerImg.objects.create(img_path_id= crawler.pk, path= analyzer.download_img(i))

impudo-ui/interface/views.py
from django.core.exceptions import ValidationError
from django.http import HttpResponse
from django.shortcuts import redirect, render

from interface.forms import TemplateForm
from interface.models import Template, Crawler, CrawlerImgPath
from interface.tasks import scrape

NO_SELECTION_ERROR = 'You need to select at least one option'

def home_page(request):
    return render(request, 'home.html', {'form': TemplateForm()})

def view_template(request, template_id):
    item = Template.objects.get(id=template_id)
    form = TemplateForm()
    if request.method == 'POST':
        form = TemplateForm(data=request.POST, instance=item)
        if form.is_valid():
            # Activate selected records
            for record_id in request.POST.getlist('record'):
                record = Crawler.objects.get(id=int(record_id))
                record.active = 1
                record.save()
            for img_id in request.POST.getlist('img'):
                img = CrawlerImgPath.objects.get(id=int(img_id))
                img.active = 1
                img.save()
            # Only inactive records are kept in database
            active_paths = list(Crawler.objects.filter(template_id=template_id, active=1))
            active_imgs = list(CrawlerImgPath.objects.filter(template_id=template_id, active=1))
            Crawler.objects.filter(template_id=template_id).delete()
            CrawlerImgPath.objects.filter(template_id=template_id).delete()
            form.save_active_paths(active_paths)
            form.save_active_imgs(active_imgs)

            if 'dispatch' in request.POST:
                #TODO: redirect to manage page
                if not 'record' in request.POST:
                    return render(request, 'template.html',
                        {'form': form, 'item': item,
                         'not_selected_error': NO_SELECTION_ERROR})
                else:
                    scrape.delay(template_id)
                    return render(request, 'home.html', {'form': TemplateForm()})

            # Delete xpath records before re-searching them
            Crawler.objects.filter(template_id=template_id).delete()
            CrawlerImgPath.objects.filter(template_id=template_id).delete()
            item = form.save()
            #TODO: which exceptions do I need?
            try:
                form.analyze()
                return redirect(item)
            except:
                return render(request, '404.html')
        else:
            return render(request, 'template.html', {'form': form, 'item': item,})
    else:
        return render(
                request, 'template.html', {
                    'item': item,
                    'form': TemplateForm(initial={
                        'url': item.url, 'desc': item.desc, }),
                    }
                )

def new_template(request):
    form = TemplateForm(data=request.POST)
    if form.is_valid():
        item = form.save()
        form.analyze()
        return redirect(item)
    else:
        return render(request, 'home.html', {'form': form})

impudo-ui/interface/templates/base.html
<!DOCTYPE html>
<html lang='en'>

<head>
  <meta charset='utf-8'>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <title>Impudo Crawler</title>
  <link href='/static/bootstrap/css/bootstrap.min.css' rel='stylesheet'>
  <link href='/static/base.css' rel='stylesheet'>
</head>

<body>
  <div class='containter'>
     <div class="navbar navbar-default navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">
            <div class="navbar-header">
              {% block links %}{% endblock %}
            </div>
          </div>
        </div>
     </div>
    <div class='row'>
      <div class='col-md-6 col-md-offset-3 jumbotron'>
        <div class='text-center'>
          <h1>{% block header_text %}{% endblock %}</h1>
        </div>
      </div>
    </div>
    <div class='row'>
      <div class='col-md-6 col-md-offset-3'>
        <div class='text-center'>
          {% block input %}
          {% endblock %}
        </div>
      </div>
    </div>
      <div class='col-md-6 col-md-offset-3'>
        {% block table %}
        {% endblock %}
      </div>
    </div>
  </div>
  
</body>

impudo-ui/interface/templates/bs_admin_base.html
{% load i18n admin_static bootstrapped_goodies_tags %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html xmlns="http://www.w3.org/1999/xhtml" lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    {% block extrastyle %}{% endblock %}

    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/overrides.css" %}" />
    {% if LANGUAGE_BIDI %}
    <link href="{% static "bootstrap-rtl/css/bootstrap-rtl.min.css" %}" rel="stylesheet"/>
    <link href="{% static "bootstrap-rtl/css/bootstrap-flipped.min.css" %}" rel="stylesheet"/>
    {% endif %}

    <script type="text/javascript">
    //<![CDATA[
        window.__admin_media_prefix__ = "{% filter escapejs %}{% static "admin/" %}{% endfilter %}";
        window.__admin_utc_offset__ = "{% filter escapejs %}{% now "Z" %}{% endfilter %}";
    //]]>
    </script>
    <script src="{% static "admin/js/jquery-1.9.1.min.js" %}"></script>
    <script src="{% static "admin/js/jquery-migrate-1.2.1.min.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>

    {% block extrahead %}{% endblock %}

    {% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
    <script type="text/javascript">
    //<![CDATA[
            (function($) {
                $(document).ready(function() {
                    $('input[type="submit"]').addClass('btn');
                    $('[title]').tooltip();
                });
            }(jQuery));
    //]]>
    </script>
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}">

<!-- Container -->
<div class="container">

    {% if not is_popup %}
    <!-- Header -->
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    {% block branding %}{% endblock %}
                </div>
                <div id="header-navbar-collapse" class="navbar-collapse collapse navbar-{% if LANGUAGE_BIDI %}left{% else %}right{% endif %}">
                    <ul class="nav navbar-nav">
                        {% if has_permission %}
                        {% block usertools %}
                        <li class="dropdown">
                            {% block welcome-msg %}
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans 'Welcome,' %} <strong>{% filter force_escape %}{% firstof user.get_short_name user.get_username %}{% endfilter %}</strong> <span class="caret"></span></a>
                            {% endblock %}
                            <ul class="dropdown-menu">
                                {% if site_url %}
                                    <li><a href="{{ site_url }}">{% trans 'View site' %}</a></li>
                                {% endif %}
                                {% if user.is_active and user.is_staff %}
                                    {% url 'django-admindocs-docroot' as docsroot %}
                                    {% if docsroot %}
                                        <li><a href="{{ docsroot }}">{% trans 'Documentation' %}</a></li>
                                    {% endif %}
                                {% endif %}
                                {% if user.has_usable_password %}
                                <li><a href="{% url 'admin:password_change' %}">{% trans 'Change password' %}</a></li>
                                {% endif %}
                                <li><a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a></li>
                            </ul>
                        </li>
                        {% endblock %}
                        {% block languages %}
                        <li class="divider-vertical"></li>
                        {% language_selector %}
                        {% endblock languages %}
                        {% block logs %}
                        <li class="dropdown" id="recent-actions-module">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans 'Recent Actions' %} <b class="caret"></b></a>
                            {% load log %}
                            {% get_admin_log 10 as admin_log for_user user %}
                            <ul class="dropdown-menu">
                                {% for entry in admin_log %}
                                <li class="{% if entry.is_addition %}addlink{% endif %}{% if entry.is_change %}changelink{% endif %}{% if entry.is_deletion %}deletelink{% endif %}">
                                    <a href="{% if entry.is_deletion or not entry.get_admin_url %}#{% else %}{{ entry.get_admin_url }}{% endif %}">
                                        <i class="glyphicon glyphicon-{% if entry.is_addition %}plus{% endif %}{% if entry.is_change %}edit{% endif %}{% if entry.is_deletion %}remove{% endif %}"></i>
                                        {{ entry.object_repr }}
                                        {% if entry.content_type %}
                                        <span class="mini quiet">({% filter capfirst %}{{ entry.content_type }}{% endfilter %})</span>
                                        {% else %}
                                        <span class="mini quiet">({% trans 'Unknown content' %})</span>
                                        {% endif %}
                                    </a>
                                </li>
                                {% empty %}
                                <li class="disabled"><a href="#">{% trans 'None available' %}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                        {% endblock %}
                        {% block userlinks %}
                        {% url 'django-admindocs-docroot' as docsroot %}
                        {% if docsroot %}
                        <li class="divider-vertical"></li>
                        <li><a href="{{ docsroot }}">{% trans 'Documentation' %}</a></li>
                        {% endif %}
                        {% endblock %}
                        {% endif %}
                        {% block nav-global %}{% endblock %}
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>
    </div>
    <!-- END Header -->
    <div class="row">
        <div class="col-sm-12">
            {% block breadcrumbs %}
            {% endblock %}
        </div>
    </div>
    {% endif %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block navbar %}
        <div class="navbar navbar-default">
            <div class="navbar-inner">
                {% block pretitle %}{% endblock %}
                    <div class="navbar-header">
                        {% block content-navbar-collapse %}
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#content-navbar-collapse" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        {% endblock %}
                    </div>
                {% block object-tools %}{% endblock %}
            </div>
        </div>
        {% endblock navbar %}

        {% block messages %}
        {% if messages %}
        <div class="row">
            <div class="col-sm-12">
                {% for message in messages %}
                <div class="alert {{ message.tags|default:"alert-info" }}">
                    {{ message|capfirst }}
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
        {% endblock messages %}

        {% block content %}{{ content }}{% endblock %}
        {% block sidebar %}{% endblock %}
    </div>
    <!-- END Content -->

    {% block footer %}<footer id="footer"></footer>{% endblock %}
</div>
<!-- END Container -->

</body>
</html>

impudo-ui/interface/templates/bs_admin_base_site.html
{% extends "admin/base.html" %}
{% load i18n %}{% load admin_static bootstrapped_goodies_tags %}

{% block title %}{% render_with_template_if_exist "admin/admin_title.html" title %} | {{ site_title|default:_('Django site admin') }}{% endblock %}

{% block branding %}
<a class="navbar-brand" href="{% url 'admin:index' %}">{% if site_header %}{{ site_header }}{% else %}{% render_with_template_if_exist "admin/admin_title.html" _('Django administration') %}{% endif %}</a>
<a class="navbar-brand" href="{% url 'home' %}">Create Crawler</a>
{% endblock %}

{% block nav-global %}{% endblock %}

impudo-ui/interface/templates/bs_admin_change_form.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls admin_static admin_modify bootstrapped_goodies_tags %}

{% block extrahead %}{{ block.super }}
{% url 'admin:jsi18n' as jsi18nurl %}
<script type="text/javascript" src="{{ jsi18nurl|default:"../../../jsi18n/" }}"></script>
{{ media }}
{% endblock %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />{% endblock %}

{% block coltype %}{% if ordered_objects %}colMS{% else %}colM{% endif %}{% endblock %}

{% block bodyclass %}{{ block.super }} {{ opts.app_label }}-{{ opts.object_model }} change-form{% endblock %}

{% if not is_popup %}
{% block breadcrumbs %}
<ul class="breadcrumb">
<li><a href="{% url 'admin:index' %}">{% trans 'Home' %}</a></li>
<li><a href="{% url 'admin:app_list' app_label=opts.app_label %}">{% with app_label=opts.app_config.verbose_name|default:opts.app_label %}{{ app_label|title }}{% endwith %}</a></li>
<li>{% if has_change_permission %}<a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>{% else %}{{ opts.verbose_name_plural|capfirst }}{% endif %}</li>
<li>{% if add %}{% trans 'Add' %} {{ opts.verbose_name }}{% else %}{{ original|truncatewords:"18" }}{% endif %}</li>
</ul>
{% endblock %}
{% endif %}

{% block object-tools %}
{% if change %}{% if not is_popup %}
<div id="content-navbar-collapse" class="navbar-collapse collapse">
  <ul class="nav navbar-nav navbar-right">
    {% block object-tools-items %}
    <li>
        {% url opts|admin_urlname:'history' original.pk|admin_urlquote as history_url %}
        <a role="button" href="{% add_preserved_filters history_url %}" class="historylink">{% trans "History" %}</a>
    </li>
    {% if has_absolute_url %}<li><a href="{% url 'admin:view_on_site' content_type_id original.pk %}" class="viewsitelink">{% trans "View on site" %}</a></li>{% endif %}
    {% endblock %}
  </ul>
</div>
{% endif %}{% endif %}
{% endblock %}

{% block content %}

{% with module_name=opts.model_name|lower|slugify %}
    {% render_with_template_if_exist opts.app_label|lower|add:"/admin_model_"|add:module_name|add:"_change_form.html" "" %}
{% endwith %}


<form class="form-horizontal" {% if has_file_field %}enctype="multipart/form-data" {% endif %}action="{{ form_url }}" method="post" id="{{ opts.model_name }}_form" novalidate>{% csrf_token %}{% block form_top %}{% endblock %}
    {% if errors %}
    <div class="alert alert-danger">
        {% if errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
        {{ adminform.form.non_field_errors }}
    </div>
    {% endif %}

    {% if save_on_top %}{% block submit_buttons_top %}{% submit_row %}{% endblock %}{% endif %}

    <div id="content-main">
        <div>
        {% if is_popup %}<input type="hidden" name="_popup" value="1" />{% endif %}

        {% block field_sets %}
        {% for fieldset in adminform %}
          {% include "admin/includes/fieldset.html" with group_column_width=adminform|form_fieldset_column_width %}
        {% endfor %}
        {% endblock %}

        {% block after_field_sets %}{% endblock %}

        {% block inline_field_sets %}
        {% for inline_admin_formset in inline_admin_formsets %}
            {% include inline_admin_formset.opts.template %}
        {% endfor %}
        {% endblock %}

        {% block after_related_objects %}{% endblock %}

        {% block admin_change_form_document_ready %}

        <script type="text/javascript">
            (function($) {
                $(document).ready(function() {
                    $('.add-another').click(function(e) {
                        e.preventDefault();
                        showAddAnotherPopup(this);
                    });
                    $('.related-lookup').click(function(e) {
                        e.preventDefault();
                        showRelatedObjectLookupPopup(this);
                    });
                {% if adminform and add %}
                    $('form#{{ opts.model_name }}_form :input:visible:enabled:first').focus()
                {% endif %}
                });
            })(django.jQuery);
        </script>
        {% endblock %}

        {# JavaScript for prepopulated fields #}
        {% prepopulated_fields_js %}

        </div>
    </div>

    <div class="form-actions">
        {% block submit_buttons_bottom %}{% submit_row %}{% endblock %}
    </div>
</form>
{% endblock %}

impudo-ui/interface/templates/home.html
{% extends 'base.html' %}
{% block links %}
  <a class="navbar-brand" href="{% url 'admin:index' %}">Manage Crawler</a> 
  <a class="navbar-brand" href="{% url 'home' %}">Create Crawler</a>
{% endblock %}
{% block header_text %}Create Crawler Template{% endblock %}

{% block input %}
  <form method='POST' action={% url 'new_template' %}>
    {{ form.url }}
    <br>
    {{ form.desc }}
    <br>
    <input id='id_submit' type='submit' value='Generate crawler template' class='btn btn-default'/>
    {% csrf_token %}
    {% if form.errors %}
      <div class='form-group has-error'>
        <span class='help-block'>{{ form.url.errors }}</span>
        <span class='help-block'>{{ form.desc.errors }}</span>
      </div>
    {% endif %}
  </form>
{% endblock %}

impudo-ui/interface/templates/template.html
{% extends 'base.html' %}
{% block links %}
<a class="navbar-brand" href="{% url 'admin:index' %}">Manage Crawler</a> 
<a class="navbar-brand" href="{% url 'home' %}">Create Crawler</a>
{% endblock %}
{% block header_text %}Crawler: {{ item.url_abbr }}{% endblock %}
{% block table %}

  <form method='POST' action={% url 'view_template' item.id %}> 
    <div class='row'>
      <div class='col-xs-2'></div>
      <div class='col-xs-5'><h5>Your Input</h5></div>
      <div class='col-xs-5'><h5>Crawler Output</h5></div>
    </div>
    <div class='row top-buffer'>
      <div class='col-xs-2'><h5>Scraping URL</h5></div>
      <div class='col-xs-5 align-top'>{{ form.url }}</div>
      <div class='col-xs-5'>{{ item.url }}</div>
    </div>
    <div class='row top-buffer'>
      <div class='col-xs-2'><h5>Text to Scrape</h5></div>
      <div class='col-xs-5'>{{ form.desc }}</div>
      <div class='col-xs-5'>
        {% for record in item.crawler_set.all %}
        <label><input type='checkbox' name='record' value={{ record.id }}>{{ record.content }}<br></label>
        {% endfor %}
      </div>
    </div>
    <div class='row top-buffer'>
      <div class='col-xs-2'><h5>Images to Scrape</h5></div>
      <div class='col-xs-10'>
        {% for path in item.crawlerimgpath_set.all %}
        <div class='row'>
          <label>
            <div class='col-xs-2'>
              <input type='checkbox' name='img' value={{ path.id }}>
            </div>
            <div class='col-xs-10'>
                {% for img in path.crawlerimg_set.all %}
                {{ img.img | safe }}
                {% endfor %}
            </div>
          <label>
        </div>
        {% endfor %}
      </div>
    </div>
    <div class='row top-buffer'>
      <div class='col-xs-2'></div>
      <div class='col-xs-5'>
        <input id='id_submit' type='submit' name='change' value='Change crawler template' class='btn btn-default'/>
      </div>
      <div class='col-xs-5'>
        <input id='id_dispatch' type='submit' name='dispatch' value='Save & dispatch crawler' class='btn btn-default'/>
      </div>
      {% csrf_token %}
    </div>
    {% if form.errors or not_selected_error %}
      <div class='text-center'>
        <div class='form-group has-error'>
          <span class='help-block'>{{ form.url.errors }}</span>
          <span class='help-block'>{{ form.desc.errors }}</span>
          <span class='help-block'>{{ not_selected_error }}</span>
        </div>
      </div>
    {% endif %}
  </form>
{% endblock %}